import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api} from '../services/api';
import {useSocket} from '../hooks/useSocket';
import StatCard from '../components/StatCard';
import {Bed,Ambulance,AlertTriangle,CheckCircle2,ShieldPlus} from 'lucide-react';

export default function HospitalDashboard(){
  const [d,setD]=useState(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[antivenom,setAntivenom]=useState({available:false,units:0}),[saving,setSaving]=useState(false);
  const navigate=useNavigate();
  const load=()=>{setError('');return api.get('/hospitals/dashboard/me').then(r=>{const data=r.data.data;setD(data);setAntivenom({available:data.hospital.antivenomAvailable,units:data.hospital.antivenomUnits});}).catch(err=>{if(err.response?.status===404&&err.response?.data?.error==='NOT_FOUND'){navigate('/hospital/setup',{replace:true});return;}setError(err.response?.data?.message||'Unable to load hospital dashboard');}).finally(()=>setLoading(false));};
  useEffect(load,[]);
  useSocket({'emergency:hospital-notified':e=>{setToast(`New ${e.priority} emergency nearby`);load()}});
  const action=promise=>promise.then(load).catch(err=>setError(err.response?.data?.message||'Unable to update emergency'));
  const accept=id=>action(api.post(`/emergencies/${id}/accept`));
  const assign=id=>action(api.post(`/emergencies/${id}/assign-ambulance`,{}));
  const updateAntivenom=async event=>{event.preventDefault();setError('');setSaving(true);try{await api.put(`/hospitals/${d.hospital._id}/resources`,{antivenomAvailable:antivenom.available,antivenomUnits:Number(antivenom.units)});await load();}catch(err){setError(err.response?.data?.message||'Unable to update antivenom resource');}finally{setSaving(false);}};
  return <div className="space-y-6">{toast&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{toast}</div>}{error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{loading&&!d&&<div className="rounded-2xl border bg-white p-6 text-slate-500">Loading hospital dashboard...</div>}{d&&<><div><h1 className="text-3xl font-black">{d.hospital.name}</h1><p className="text-slate-500">Hospital command center</p></div><div className="grid gap-4 md:grid-cols-5"><StatCard label="Active emergencies" value={d.metrics.active} icon={AlertTriangle}/><StatCard label="Available beds" value={d.metrics.availableBeds} icon={Bed}/><StatCard label="Available ambulances" value={d.metrics.availableAmbulances} icon={Ambulance}/><StatCard label="Completed cases" value={d.metrics.completed} icon={CheckCircle2}/><StatCard label="Antivenom" value={d.hospital.antivenomAvailable?`${d.hospital.antivenomUnits} units`:'Unavailable'} icon={ShieldPlus}/></div><section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Antivenom resource</h2><p className="text-sm text-slate-500">{d.hospital.antivenomAvailable?'Available':'Unavailable'} · {d.hospital.antivenomUnits} units</p></div><ShieldPlus className="text-slate-400"/></div><form className="mt-5 flex flex-wrap items-end gap-4" onSubmit={updateAntivenom}><label className="flex items-center gap-2"><input type="checkbox" checked={antivenom.available} onChange={e=>setAntivenom({...antivenom,available:e.target.checked})}/> Antivenom available</label><label className="flex flex-col gap-1 text-sm text-slate-600">Units<input className="w-32 rounded-xl border px-3 py-2 text-slate-900" type="number" min="0" value={antivenom.units} onChange={e=>setAntivenom({...antivenom,units:e.target.value})}/></label><button disabled={saving} className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-60">{saving?'Saving...':'Save antivenom'}</button></form></section><section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-black">Emergency requests</h2><span className="text-sm text-slate-500">Critical first</span></div><div className="mt-5 space-y-3">{d.requests.map(e=><div key={e._id} className="flex flex-col gap-3 rounded-2xl border p-4 md:flex-row md:items-center md:justify-between"><div><div className="font-bold">{e.patientId?.name||'Patient'} - {e.priority}</div><div className="text-sm text-slate-500">{e.emergencyType} - {e.status}</div></div><div className="flex gap-2">{e.status==='HOSPITAL_NOTIFIED'&&<button onClick={()=>accept(e._id)} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">Accept</button>}{e.status==='ACCEPTED'&&<button onClick={()=>assign(e._id)} className="rounded-lg bg-red-600 px-3 py-2 text-sm font-bold text-white">Assign ambulance</button>}</div></div>)}</div></section></>}</div>;
}
