import Ambulance from '../models/Ambulance.js'; import EmergencyRequest from '../models/EmergencyRequest.js'; import Hospital from '../models/Hospital.js'; import { ok } from '../utils/api.js'; import { AppError } from '../utils/errors.js'; import { toPoint } from '../utils/geo.js';
async function hospitalFor(req){return Hospital.findOne({ownerId:req.user._id});}
async function canManage(req, ambulance){if(!ambulance)throw new AppError('Ambulance not found',404,'NOT_FOUND');if(req.user.role==='admin')return true;if(req.user.role==='ambulance'&&String(ambulance.userId)!==String(req.user._id))throw new AppError('You can only manage your assigned ambulance',403,'FORBIDDEN');if(req.user.role==='hospital'){const hospital=await hospitalFor(req);if(!hospital||String(ambulance.hospitalId)!==String(hospital._id))throw new AppError('You can only manage your hospital ambulances',403,'FORBIDDEN');}return true;}
async function mine(req){if(req.user.role==='ambulance')return Ambulance.findOne({userId:req.user._id});const hospital=await hospitalFor(req);return hospital?Ambulance.findOne({hospitalId:hospital._id}):null;}
export async function list(req,res){let q={};if(req.user.role==='ambulance')q={userId:req.user._id};if(req.user.role==='hospital'){const hospital=await hospitalFor(req);q={hospitalId:hospital?._id};}ok(res,{ambulances:await Ambulance.find(q).populate('hospitalId')});}
export async function create(req,res){const hospital=await hospitalFor(req);if(!hospital)throw new AppError('Hospital profile not found',404,'HOSPITAL_PROFILE_REQUIRED');const a=await Ambulance.create({...req.body,hospitalId:hospital._id});ok(res,{ambulance:a},'Ambulance created',201);}
export async function update(req,res){const a=await Ambulance.findById(req.params.id);await canManage(req,a);const allowed=['vehicleNumber','driverName','driverPhone','type','capacity','equipment'];for(const key of allowed)if(req.body[key]!==undefined)a[key]=req.body[key];await a.save();ok(res,{ambulance:a});}
export async function location(req,res){const a=req.user.role==='ambulance'?await mine(req):await Ambulance.findById(req.body.ambulanceId||req.params.id);await canManage(req,a);if(!Number.isFinite(Number(req.body.lat))||!Number.isFinite(Number(req.body.lng)))throw new AppError('Valid coordinates required',422,'VALIDATION_ERROR');a.currentLocation=toPoint(req.body.lat,req.body.lng);await a.save();const e=await EmergencyRequest.findOne({ambulanceId:a._id,status:{$nin:['COMPLETED','CANCELLED','REJECTED']}});if(e){req.app.get('io')?.to(`user:${e.patientId}`).emit('ambulance:location-update',{ambulanceId:a._id,location:a.currentLocation});req.app.get('io')?.to(`emergency:${e._id}`).emit('ambulance:location-update',{ambulanceId:a._id,location:a.currentLocation});}ok(res,{ambulance:a});}
export async function status(req,res){const a=await Ambulance.findById(req.params.id);await canManage(req,a);const allowed=['AVAILABLE','ASSIGNED','EN_ROUTE','ARRIVED','TRANSPORTING','COMPLETED','OFFLINE'];if(!allowed.includes(req.body.status))throw new AppError('Invalid ambulance status',422,'VALIDATION_ERROR');if(req.body.status==='AVAILABLE'&&await EmergencyRequest.exists({ambulanceId:a._id,status:{$nin:['COMPLETED','CANCELLED','REJECTED']}}))throw new AppError('Ambulance is assigned to an active emergency',409,'AMBULANCE_UNAVAILABLE');a.status=req.body.status;await a.save();ok(res,{ambulance:a});}
export async function simulate(req,res){const a=await Ambulance.findById(req.params.id);await canManage(req,a);const e=await EmergencyRequest.findOne({ambulanceId:a._id,status:{$in:['AMBULANCE_ASSIGNED','AMBULANCE_EN_ROUTE']}});if(!e)return ok(res,{message:'No active emergency for simulation'});const start=a.currentLocation.coordinates,end=e.patientLocation.coordinates;for(let i=1;i<=10;i++){setTimeout(async()=>{const lng=start[0]+(end[0]-start[0])*i/10,lat=start[1]+(end[1]-start[1])*i/10;await Ambulance.findByIdAndUpdate(a._id,{currentLocation:toPoint(lat,lng),status:'EN_ROUTE'});req.app.get('io')?.to(`user:${e.patientId}`).emit('ambulance:location-update',{ambulanceId:a._id,location:toPoint(lat,lng)});},i*1000);}await EmergencyRequest.findByIdAndUpdate(e._id,{status:'AMBULANCE_EN_ROUTE'});ok(res,{message:'Demo movement started'});}
