import test from 'node:test'; import assert from 'node:assert/strict'; import {calculateRankingValue} from '../src/services/ranking.js'; import {rankHospitals} from '../src/services/emergencyService.js';
test('dynamic ranking value rewards available resources',()=>{const a=calculateRankingValue({distanceKm:4,hospital:{availableBeds:10,totalBeds:50,emergencyAvailable:true,icuAvailable:true,oxygenAvailable:true,departments:['Emergency']},ambulanceAvailable:true});const b=calculateRankingValue({distanceKm:4,hospital:{availableBeds:0,totalBeds:50,emergencyAvailable:true,icuAvailable:false,oxygenAvailable:false,departments:['Emergency']},ambulanceAvailable:false});assert.ok(a>b);});
test('venom emergencies prefer stocked antivenom hospitals',()=>{const stocked=calculateRankingValue({distanceKm:4,emergencyType:'Snakebite',hospital:{availableBeds:10,totalBeds:50,emergencyAvailable:true,icuAvailable:true,oxygenAvailable:true,antivenomAvailable:true,antivenomUnits:8,departments:['Emergency']},ambulanceAvailable:true});const unstocked=calculateRankingValue({distanceKm:4,emergencyType:'Snakebite',hospital:{availableBeds:10,totalBeds:50,emergencyAvailable:true,icuAvailable:true,oxygenAvailable:true,antivenomAvailable:false,antivenomUnits:0,departments:['Emergency']},ambulanceAvailable:true});assert.ok(stocked>unstocked);});
test('blood requests prefer hospitals with the patient blood group',()=>{const compatible=calculateRankingValue({distanceKm:4,requestedResources:['BLOOD'],bloodGroup:'O+',hospital:{availableBeds:10,totalBeds:50,emergencyAvailable:true,icuAvailable:true,oxygenAvailable:true,bloodBank:{'O+':8},departments:['Emergency']},ambulanceAvailable:true});const unavailable=calculateRankingValue({distanceKm:4,requestedResources:['BLOOD'],bloodGroup:'O+',hospital:{availableBeds:10,totalBeds:50,emergencyAvailable:true,icuAvailable:true,oxygenAvailable:true,bloodBank:{'O+':0},departments:['Emergency']},ambulanceAvailable:true});assert.ok(compatible>unavailable);});
test('ICU bed requests prefer ICU hospitals with available beds',()=>{const suitable=calculateRankingValue({distanceKm:4,requestedResources:['ICU_BED'],hospital:{availableBeds:10,totalBeds:50,emergencyAvailable:true,icuAvailable:true,oxygenAvailable:true},ambulanceAvailable:false});const unsuitable=calculateRankingValue({distanceKm:4,requestedResources:['ICU_BED'],hospital:{availableBeds:10,totalBeds:50,emergencyAvailable:true,icuAvailable:false,oxygenAvailable:true},ambulanceAvailable:false});assert.ok(suitable>unsuitable);});
test('antivenom availability outranks a closer hospital without stock',()=>{const ranked=rankHospitals([{distanceKm:2,_rankingValue:0.99,emergencyAvailable:true,antivenomAvailable:false,antivenomUnits:0},{distanceKm:8,_rankingValue:0.5,emergencyAvailable:true,antivenomAvailable:true,antivenomUnits:5}],['ANTIVENOM']);assert.equal(ranked[0].antivenomUnits,5);});
test('distance orders hospitals that both have antivenom',()=>{const ranked=rankHospitals([{distanceKm:3,_rankingValue:0.5,emergencyAvailable:true,antivenomAvailable:true,antivenomUnits:2},{distanceKm:6,_rankingValue:0.99,emergencyAvailable:true,antivenomAvailable:true,antivenomUnits:10}],['ANTIVENOM']);assert.equal(ranked[0].distanceKm,3);});
test('zero antivenom units count as unavailable',()=>{const ranked=rankHospitals([{distanceKm:1,_rankingValue:0.5,emergencyAvailable:true,antivenomAvailable:true,antivenomUnits:0},{distanceKm:5,_rankingValue:0.1,emergencyAvailable:true,antivenomAvailable:true,antivenomUnits:4}],['ANTIVENOM']);assert.equal(ranked[0].antivenomUnits,4);});
test('distance remains the fallback for hospitals without antivenom',()=>{const ranked=rankHospitals([{distanceKm:2,_rankingValue:0.5,emergencyAvailable:true,antivenomAvailable:false,antivenomUnits:0},{distanceKm:4,_rankingValue:0.5,emergencyAvailable:true,antivenomAvailable:false,antivenomUnits:0}],['ANTIVENOM']);assert.equal(ranked[0].distanceKm,2);});
